{% set name = "libtermkey" %}
{% set version = "0.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.leonerd.org.uk/code/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6945bd3c4aaa83da83d80a045c5563da4edd7d0374c62c0d35aec09eb3014600

build:
  number: 2
  run_exports:
    - {{ pin_subpackage('libtermkey', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake  # [win]
    - make  # [unix]
    - ninja  # [win]
    - pkg-config  # [unix]
  host:
    - libtool  # [unix]
    - ncurses  # [unix]
    - unibilium

test:
  commands:
    - test -f ${PREFIX}/lib/libtermkey${SHLIB_EXT}  # [unix]

about:
  home: http://www.leonerd.org.uk/code/libtermkey/
  license: MIT
  license_file: LICENSE
  summary: Library for processing keyboard entry from the terminal
  dev_url: http://www.leonerd.org.uk/code/libtermkey/

extra:
  recipe-maintainers:
    - anjos
    - danielnachun
